version: '3'

services:
    web:
      restart: always
      command: >
              bash -c "python manage.py migrate
                       python manage.py collectstatic --no-input --clear
                       gunicorn examchecker_back.wsgi -b 0.0.0.0:8000 --workers 3"
      build: .
      volumes:
        - web-static:/code/static
      ports:
        - "8000:8000"
    nginx:
      restart: always
      build: ./nginx/
      ports:
        - "80:80"
      volumes:
        - web-static:/www/static
      links:
        - web:web
volumes:
  web-static: